// Importing createSlice function from Redux Toolkit
import { createSlice } from '@reduxjs/toolkit'

// Defining the initial state for the counter slice
const initialState = {
  value: 0, // Starting the counter with a value of 0
}

// Creating a slice of the Redux store called 'counter' using createSlice
export let CounterSlicer = createSlice({
  name: 'counter', // Assigning a name to the slice, useful for debugging
  initialState, // Setting the initial state for the counter slice
  reducers: {
    // Defining actions to modify the state when dispatched

    // Incrementing the value in the state by 1
    increment: (state) => {
      state.value++
    },

    // Decrementing the value in the state by 1
    decrement: (state) => {
      state.value--
    }
  }
})

// Extracting the actions (increment and decrement) from the created slice
export const { increment, decrement } = CounterSlicer.actions

// Exporting the reducer function generated by createSlice
export default CounterSlicer.reducer
